### ISSUE TITLE
The imagelightbox is used in the opera

### ISSUE THREAD

**Issue by Salon-sai** [rejas/imagelightbox#14] opened 2015-04-22 09:57 UTC
I use the imagelightbox in different browsers and find the opera (mobile) not supporting quitOnDocClick. After being clicked the overlay,  view will start the image which you click behind overlay. I try to test the demo in the opera(mobile) . The demo has the same problem.

**Comment by rejas** [comment] 2015-04-24 09:52
which opera version are you using exactly? i could not reproduce it with the Opera-Browser For Android v28

**Comment by Salon-sai** [comment] 2015-04-27 13:26
I use the opera version is v10 and wechat. I find the problem is the touchend event is disabled in the browser, so I am change it in the demo. By the way , I think the loading image is not supported to dynamically add image, if you use the ajax in the web. Thus , I hope you can make it support. And I make it support with your imagelightbox in my github. I hope you find the proposals practical in my code.

**Comment by rejas** [comment] 2015-04-27 21:14
v10 seems a little outdated, but if your fixes work and don't have regressions on other browsers feel free to open a pull request. 
as for your "dynamically adding an image"-feature: would like to see it merged, please open a pull request (optimally with some addendum to the documentation)

**Comment by Salon-sai** [comment] 2015-05-02 07:56
I pull the code and document to github. if you have some question , you can contact with me in github

**Comment by rejas** [comment] 2015-05-02 11:33
Tahnk you for the submission. I will comment directly in the pull-request.

**Closed** 2015-05-07 03:53 UTC
