### ISSUE TITLE
iOS8 Safari arrow button sometimes skips image...

### ISSUE THREAD

**Issue by hanwiz** [rejas/imagelightbox#31] opened 2016-05-20 19:47 UTC
Arrow button usually skips the next image and show the next, next image. This behavior doesn't occur on the original imagelightbox nor using swipe.

**Comment by rejas** [comment] 2016-05-21 09:30
I only have ios9 here in my simulator and cant reproduce it. Do you have an ios9 device to confirm?

**Comment by hanwiz** [comment] 2016-07-18 14:07
Yep, I don't see any problem in ios9 simulator, too. Any way, I think it's related to the preload function. What does this load function do?

$('<img />').attr('src', nextTarget.attr('href')).load();

**Comment by rejas** [comment] 2016-07-21 15:10
That line creates a new img tag, adds the href of the nextTarget to it  as the src and loads the img. As for the IOS8 problem, is IOS8 still relevant? Shouldnt the vast majority of users be on IOS9 by now?

**Comment by hanwiz** [comment] 2016-07-22 16:09
I mean the "load" function at the end of the line because that is one difference from the original version. In jQuery, load without argument doesn't have any meaning and I think it does cause some issue on ios 8. After removing the load function, my ios 8 simulator doesn't skip the image any more.

**Comment by rejas** [comment] 2016-07-23 09:31
The meaning of that "load" is to preload the next image, for how the call works see this link: https://stackoverflow.com/questions/23158635/using-jquery-load-with-no-arguments-to-preload-an-image A maybe cleaner way (since load() was deprecated in jquery 1.8) would be this:
`(new Image()).src = nextTarget.attr('href');`
Could you test this line for IOS8?

**Comment by rejas** [comment] 2016-07-23 09:33
You can also test it by checking out the branch "issue31_preload"

**Comment by hanwiz** [comment] 2016-07-25 15:26
It's still skipping images, but I found a real issue on this. Currently, ios8, for the right arrow, when you click about left half of the arrow, click and touchend event both happens to skip the image. 

As we can make the image skip using double tap or double click on other devices in similar way, can we prevent this using some kind of delay?

**Comment by rejas** [comment] 2016-07-25 20:49
Could you try it out with the new version 0.5.0? Maybe the fixes for jquery3 had some impact on your problem.

**Comment by hanwiz** [comment] 2016-07-26 15:36
Oh my god! 0.5.0 removes the load function at the end of the line and this should work as I commented previously.

**Comment by rejas** [comment] 2016-07-26 16:17
So I guess I can close this issue....

**Closed by rejas** 2016-07-26 16:17 UTC
